- name: Install MySQL Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - libmysqlclient-dev
  tags:
    - mysql-server

- name: Install the Python MySQL module (required for managing DB whith ansible)
  pip:
    name: MySQL-python
  tags:
    - mysql-server

- name: create database
  mysql_db:
    name: "{{database_name}}"
    state: present