# roles/nginx/tasks/main.yml
---
- name: Install nginx # the task name
  apt:                # the module to use for this task
    # the following two keys are part of the `apt` module configuration
    pkg: nginx        # indicate that the `nginx` package should be installed
    state: latest     # at the latest version
  # tag this task with `nginx` so we can easily run tasks by tag
  tags:
    - nginx

- name: Create nginx main configuration
  template:           # will use the templates defined in roles/nginx/templates
    src:nginx.conf
    dest: /etc/nginx/nginx.conf
  # the `restart nginx` handler located in roles/nginx/handlers will be triggered
  # at the end of this role
  notify: restart nginx
  tags:
    - nginx
